FROM node:lts

# Crear carpeta de trabajo en el contenedor
WORKDIR /app

# Copiar archivos necesarios para instalar dependencias
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto en el que escucha tu servidor (ajústalo si usas otro)
EXPOSE 3000

# Comando para iniciar tu servidor
CMD ["npm", "start"]
